[theme]
base = "light"
primaryColor = "#0F766E"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F3F6F8"
textColor = "#12202B"
font = "sans serif"

[client]
toolbarMode = "minimal"

[browser]
gatherUsageStats = false
